---
# Copyright 2016 LSD/UFCG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- include: monasca_pre_install.yml
- include: configure_database.yml
- include: configure_ntp.yml
- include: configure_zookeeper.yml
- include: install_kafka.yml
- include: install_storm.yml
- include: install_influxdb.yml
- include: install_schema.yml
- include: install_monasca_libraries.yml
- include: install_monasca_api.yml
- include: install_monasca_persister.yml
- include: install_monasca_notification.yml
- include: install_monasca_thresh.yml
- include: install_monasca_client.yml
- include: monasca_post_install.yml
